Models/Candidate.cs
using System.ComponentModel.DataAnnotations;

namespace BurakAkademi.Models;

public class Candidate
{
    [Required(ErrorMessage ="Email is required")]
    public string Email { get; set; } = string.Empty;
    
    
    [Required(ErrorMessage ="FirstName is required")]
    public string FirstName { get; set; } = string.Empty;


    [Required(ErrorMessage ="LastName is required")]
    public string LastName { get; set; } = string.Empty;

    public string FullName => $"{FirstName} {LastName?.ToUpper()}";

    public int Age { get; set; }

    public string SelectedCourse { get; set; } = String.Empty;
    public DateTime ApplyAt { get; set; }

    public Candidate()
    {
        ApplyAt = DateTime.Now;
    }

}

Models/ErrorViewModel.cs
namespace BurakAkademi.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Models/Repository.cs
namespace BurakAkademi.Models;

public static class Repository
{
    private static List<Candidate> applications = new();

    public static List<Candidate> Applications => applications;

    public static void Add(Candidate candidate)
    {
        applications.Add(candidate);
    }
}

Controllers/CourseController.cs
using BurakAkademi.Models;
using Microsoft.AspNetCore.Mvc;

namespace BurakAkademi.Controllers;

public class CourseController : Controller
{
    public IActionResult Index()
    {
        var model = Repository.Applications;
        return View(model);
    }

    public IActionResult Apply()
    {
        return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Apply(Candidate model)
    {
        if(Repository.Applications.Any(a => a.Email.Equals(model.Email)))
        {
            ModelState.AddModelError("","There is already an application for you.");
        }
        if(ModelState.IsValid)
        {
            Repository.Add(model);
            return View("Feedback",model);
        }
        return View();
        
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using BurakAkademi.Models;

namespace BurakAkademi.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Views/Course/Apply.cshtml
@model Candidate
@{ViewData["Title"] = "Apply";}

<h3 class="display-4">Apply</h3>

<form method="post" asp-action="apply">
    <div class="my-2">
        <label asp-for="Email"></label>
        <input asp-for="Email" class="form-control" type="text">
    </div>
    <div class="my-2">
        <label asp-for="FirstName"></label>
        <input asp-for="FirstName" class="form-control" type="text">
    </div>
    <div class="my-2">
        <label asp-for="LastName"></label>
        <input asp-for="LastName" class="form-control" type="text">
    </div>
    <div class="my-2">
        <label asp-for="Age"></label>
        <select asp-for="Age" class="form-select">
            <option value="18">18</option>
            <option value="20">20</option>
            <option value="22">22</option>
        </select>
    </div>

    <fieldset>
        <legend>Chose Only one Course</legend>

        <p>
            <input checked type="radio" asp-for="SelectedCourse" value="Asp.NET Core MVC">
            <label>Asp.NET Core MVC</label>
        </p>
        <p>
            <input type="radio" asp-for="SelectedCourse" value="Asp.NET Core API">
            <label>Asp.NET Core API</label>
        </p>
        <p>
            <input type="radio" asp-for="SelectedCourse" value="Blazor">
            <label>Blazor</label>
        </p>
    </fieldset>

    <div class="text-danger" asp-validation-summary="All"></div>

    <button class="btn btn-primary" type="submit">Apply</button>
    <a class="btn btn-warning" asp-controller="Home">Home</a>
</form>

Views/Course/Feedback.cshtml
@model Candidate
@{ViewData["Title"] = "Congratulations";}

<div class="display-4">
    Congratulations @Model.FullName
</div>
<p class="lead">Your application has been <mark>accapted.</mark></p>
<p class="lead">Many thanks for your interest.</p>
<hr>

<p class="blockquote">
    You have enrolled to <strong>@Model.SelectedCourse</strong> course.
</p>

<p class="text-muted">Applied at @Model.ApplyAt</p>

<div class="btn-group">
    <a asp-controller="Course" asp-action="Index" class="btn btn-success">Application</a>
    <a asp-controller="Home" class="btn btn-outline-success">Home</a>
</div>

Views/Course/Index.cshtml
@model List<Candidate>

<h3 class="display-6">
Applications (@Model.Count())
</h3>

@if(Model.Count() > 0 )
{
    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th>EMAİL</th>
                <th>NAME</th>
                <th>COURSE</th>
                <th>APPLY AT</th>
            </tr>
        </thead>
        <tbody>
            @foreach(var item in Model){
                <tr>
                    <td>@item.Email</td>
                    <td>@item.FullName</td>
                    <td>@item.SelectedCourse</td>
                    <td>@item.ApplyAt</td>
                </tr>
            }
        </tbody>
    </table>
}
else{
    <div class="alert alert-primary">
        There is no application. Please click <a class="alert-link" asp-controller="course" asp-action="apply">here</a> to apply.
    </div>
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Burak Akademi</h1>
    <a class="btn btn-primary" asp-action="apply" asp-controller="course">Apply to course</a>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BurakAkademi</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BurakAkademi.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BurakAkademi</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Course" asp-action="Index">Applications</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Course" asp-action="Apply">Apply</a>
                        </li>
                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - BurakAkademi - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>